[repository]
name = "hyprview"
authors = ["yz778"]
commit_pins = [
    ### [ "https://github.com/hyprwm/Hyprland/releases", "https://github.com/yz778/hyprview/releases" ] # hyprland version

    ["967c3c7404d4fa00234e29c70df3e263386d2597", "ad6496739c5c472715c4b5095c898487be00a142"] # 0.51.1
]

[hyprview]
description = "Hyprland plugin to display an interactive overview of all windows"
authors = ["yz778"]
output = "build/hyprview.so"
build = ["make -C src all"]
